import Head from "next/head";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Manda ai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to{" "}
          <a target="_blank" href="https://ismaelnascimento.com">
            Manda ai!
          </a>
        </h1>

        <div>
          <a href="/feed">
            <h2>Ir ao Feed </h2>
          </a>
          <a href="/form">
            <h2>Criar post </h2>
          </a>
        </div>
      </main>

      <footer>
        <a
          href="https://ismaelnascimento.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Ismael Ash
        </a>
      </footer>
    </div>
  );
}
